Working on the update cycle. First time I tried to edit college/1's data, the only thing I changed was the college name. That edit did not get to the table. Instead it deleted everything on that line. I rather artificially added that data manually back into the table, but that's not exactly a good long-term procedure. Current error message:
NameError at /process_form_for_editing_college/:id
undefined local variable or method `college' for #<MyApp:0x007f83050d60a8> Did you mean? @college
file: college_controller.rb location: block in <top (required)> line: 10