Created the homepage with a link to an Add Events page. The Add Events page includes a form for adding the events to be recorded in the database. The information from this form is passed to the events_controller which saves the input. Each event added is then printed out to the Add Events page in a bulleted list.
This is where I'm running into a problem with the error message:
2016-02-10 12:51:04 - NoMethodError - undefined method `each' for nil:NilClass:
  /Users/changeme/Code/web-app__swimming-competition/app/views/main/add_events.erb:13:in `block in singleton class'
  /Users/changeme/Code/web-app__swimming-competition/app/views/main/add_events.erb:-6:in `instance_eval'
  /Users/changeme/Code/web-app__swimming-competition/app/views/main/add_events.erb:-6:in `singleton class'
  /Users/changeme/Code/web-app__swimming-competition/app/views/main/add_events.erb:-8:in `__tilt_70216219145440'

The event is being added to the database and is printed to the Add Events page list, but the error message occurs and I have to reload the page to see any additions.