So, using the same logic we did to produce our success in getting a list of competitors for a given event, we tried making it so that each time you see a school listed, you see it's conference.  Getting an error.
NoMethodError at /all_schools
undefined method `conference' for nil:NilClass
file: school.rb location: conference line: 5